name: run_checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - run: sudo apt-get install pcre2-utils

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - run: go install github.com/gordonklaus/ineffassign@latest
    - run: go install honnef.co/go/tools/cmd/staticcheck@latest
    - run: go install github.com/client9/misspell/cmd/misspell@latest
    - run: go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
    - run: go install github.com/google/addlicense@latest
    - run: wget https://github.com/go-task/task/releases/download/v3.36.0/task_linux_amd64.deb
    - run: sudo dpkg -i task_linux_amd64.deb
    - run: rm task_linux_amd64.deb
    - run: task check

